@startuml
    class Cart {
        - id: UUID
        - timestamp: Date
        - customer: String
        - status: String
    }

    class Item {
        - id: UUID
        - cart: UUID
        - product: String
        - quantity: Integr
        - price: Double
    }
@enduml