version: '3.9'

services:
  cassandra:
    image: cassandra:4.0
    ports:
      - "9142:9042"
    volumes:
      - ~/apps/cassandra:/var/lib/cassandra
    environment:
      - CASSANDRA_CLUSTER_NAME=citizix